import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ChakraProvider, Flex } from '@chakra-ui/react'

import Head from 'next/head'
import Navbar from '@/Components/Navbar'

function MyApp({ Component, pageProps }: AppProps) {
  return  <ChakraProvider>
        <Head>
        <title>Muzi Zulu Home Builders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/muzulu_logo.PNG" />
      </Head>
      
  <Flex  w="100%" flexDirection="column" minH="100vh" bgColor="gray.100" m="auto" >
      <Navbar/>
        <Component {...pageProps} />       
  </Flex>
</ChakraProvider>
}

export default MyApp
